-- V1__init.sql
--
-- 2026-10-06 에 V1~V11 열한 개를 이 한 파일로 합쳤다.
-- 합치기 전 파일들은 doc/archive/migrations-before-2026-10-06/ 에 있다 (참고용, 적용 금지).
--
-- 합친 이유: 로그인이 IdP 로 넘어가면서 members 의 모양이 세 번 바뀌었고(이메일·비밀번호 추가 → public_id 추가 → 둘 삭제),
--   시드를 넣었다 지우는 파일까지 이력에 남아 있었다. 출시 직후라 지킬 데이터가 없어 한 번 갈아엎었다.
--   실제 사용자가 생긴 뒤에는 이렇게 하지 않는다 — 적용된 마이그레이션은 고치지 않고 다음 번호를 쌓는다.
--
-- 이 파일을 적용하려면 flyway_schema_history 가 없는 빈 DB 여야 한다.
--   로컬:  dropdb board && createdb board
--   운영:  앱을 내린 뒤 같은 작업. 회원·글·댓글이 전부 사라진다.


-- ─────────────────────────────────────────────────────────────
-- 회원. 식별은 IdP 가 발급한 public_id 하나로 한다. 이메일·비밀번호는 board 에 없다.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE members (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id  uuid         NOT NULL,              -- IdP account.public_id 와 같은 값. 바뀌지 않는다
    role       varchar(255) NOT NULL,              -- MemberRole enum 의 이름이 문자열로 들어간다
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_members           PRIMARY KEY (id),
    CONSTRAINT uk_members_public_id UNIQUE (public_id),
    CONSTRAINT ck_members_role      CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN'))
);


-- ─────────────────────────────────────────────────────────────
-- 프로필. 회원과 1:1. 닉네임은 board 가 가입 화면에서 받는다.
-- posts·comments 의 작성자는 members 가 아니라 profiles 를 가리킨다.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE profiles (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id  bigint       NOT NULL,
    nickname   varchar(255) NOT NULL,
    bio        varchar(256),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_profiles          PRIMARY KEY (id),
    CONSTRAINT uk_profiles_member   UNIQUE (member_id),   -- 회원 하나에 프로필 하나
    CONSTRAINT uk_profiles_nickname UNIQUE (nickname),
    CONSTRAINT fk_profiles_member   FOREIGN KEY (member_id) REFERENCES members (id)
);


-- ─────────────────────────────────────────────────────────────
-- 게시판 트리. parent_id 가 NULL 이면 최상위. 깊이 제한 없음.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE categories (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    parent_id     bigint,
    category_name varchar(100) NOT NULL,
    display_order integer      NOT NULL DEFAULT 0,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT pk_categories        PRIMARY KEY (id),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);
CREATE INDEX idx_categories_parent ON categories (parent_id);   -- 자식 조회(WHERE parent_id = ?)가 탄다


-- ─────────────────────────────────────────────────────────────
-- 게시글
-- ─────────────────────────────────────────────────────────────
CREATE TABLE posts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    author_id        bigint       NOT NULL,
    title            varchar(255) NOT NULL,
    content          text         NOT NULL,
    comments_enabled boolean      NOT NULL,
    status           varchar(255) NOT NULL,        -- PostStatus enum
    created_at       timestamp(6),
    updated_at       timestamp(6),
    CONSTRAINT pk_posts        PRIMARY KEY (id),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES profiles (id),
    CONSTRAINT ck_posts_status CHECK (status IN ('ACTIVE', 'DELETED'))
);


-- ─────────────────────────────────────────────────────────────
-- 댓글
-- ─────────────────────────────────────────────────────────────
CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    post_id    bigint       NOT NULL,
    author_id  bigint       NOT NULL,
    content    varchar(500) NOT NULL,
    status     varchar(255) NOT NULL,              -- CommentStatus enum
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT pk_comments        PRIMARY KEY (id),
    CONSTRAINT fk_comments_post   FOREIGN KEY (post_id)   REFERENCES posts (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES profiles (id),
    CONSTRAINT ck_comments_status CHECK (status IN ('ACTIVE', 'DELETED'))
);


-- ─────────────────────────────────────────────────────────────
-- 시드. 게시판 트리만 넣는다 — 화면에 보일 최소한이고, 관리자 기능(P3)이 서면 거기서 만든다.
-- 회원·글·댓글 시드는 없다. 회원은 IdP 로 로그인해 가입 화면에서 만든다.
-- id 를 직접 넣지 않는다 (identity 시퀀스가 어긋난다). 부모는 이름으로 찾는다.
-- ─────────────────────────────────────────────────────────────
INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
VALUES (NULL, '공지', 1, now(), now()),
       (NULL, '자유', 2, now(), now()),
       (NULL, '질문', 3, now(), now());

INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
SELECT id, '취미', 1, now(), now() FROM categories WHERE category_name = '자유';

INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
SELECT id, '사진', 1, now(), now() FROM categories WHERE category_name = '취미';
