-- V9__create_categories.sql
--
-- 게시판 트리.
--
-- 한 테이블이 자기를 가리킨다(parent_id). 깊이에 제한이 없다.
-- 글은 Post.category_id 로 이 트리의 어느 노드에 붙는다 — 그건 B1-4 의 V10 에서 한다.
-- 여기서는 그릇과 씨앗만 만든다.
--
-- 무한 깊이인데 어떻게 가져오나:
-- 카테고리는 수십 개다. 전부 한 번에 읽어(findAll) 자바에서 트리로 조립한다.
-- 재귀 CTE 도 경로 문자열(path)도 필요 없다.
-- B2 의 답변 트리와는 사정이 다르다 — 답변은 수만 개에 수시로 끼어들지만
-- 카테고리는 수십 개에 거의 안 바뀐다. 같은 "트리"라도 해법이 다르다.

CREATE TABLE categories (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 자기참조. 최상위는 NULL 이다.
    -- ON DELETE 를 안 줬으므로 자식이 있으면 지워지지 않는다(기본 RESTRICT).
    -- 실수로 가지를 통째로 날리는 것보다 낫다.
    parent_id     bigint REFERENCES categories(id),

    category_name varchar(100) NOT NULL,

    -- 같은 부모 안에서의 순서. 이름순이 아니라 관리자가 정한 순서로 보여야 한다.
    -- B9-7(게시판 순서·계층 변경)에서 쓴다. 나중에 ALTER 하는 것보다 지금 넣는 게 싸다.
    display_order int NOT NULL DEFAULT 0,

    created_at    timestamp(6),
    updated_at    timestamp(6)
);

-- 트리를 그릴 때 부모별로 자식을 찾는다.
CREATE INDEX idx_categories_parent ON categories(parent_id);


-- ─────────────────────────────────────────────────────────────
-- 씨앗. 화면에서 트리가 보이도록.
--
--   공지
--   자유
--    └ 취미
--        └ 사진      ← 3단계가 실제로 되는지 눈으로 보려고 넣는다
--   질문
--
-- B1-4 에서 기존 글 19개를 '자유' 로 옮긴다.
-- ─────────────────────────────────────────────────────────────

INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
VALUES (NULL, '공지', 1, now(), now()),
       (NULL, '자유', 2, now(), now()),
       (NULL, '질문', 3, now(), now());

INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
SELECT id, '취미', 1, now(), now() FROM categories WHERE category_name = '자유';

INSERT INTO categories (parent_id, category_name, display_order, created_at, updated_at)
SELECT id, '사진', 1, now(), now() FROM categories WHERE category_name = '취미';
