spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentshop
    username: ${DB_USERNAME}
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

toss:
  payments:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: https://api.tosspayments.com