-- V5__create_profiles.sql
--
-- Profile 을 더한다. 아무것도 지우지 않는다.
--
-- members.nickname 은 그대로 두고 profiles.nickname 에 복사한다.
-- 작성자(posts.author_id · comments.author_id)를 프로필로 갈아끼우는 것은
-- B0-9b 의 V6 이다. 지금 members.nickname 을 지우면
-- PostResponse 가 읽는 값이 사라져 목록·상세가 깨진다.

CREATE TABLE profiles (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  bigint NOT NULL UNIQUE REFERENCES members(id),
    nickname   varchar(255) NOT NULL UNIQUE,
    created_at timestamp(6),
    updated_at timestamp(6)
);

-- 이미 가입한 회원에게 프로필을 하나씩 만들어 준다.
-- id 를 직접 쓰지 않고 members 에서 골라 넣는다 (V2 와 같은 규칙).
-- 회원이 3명이든 3만명이든 이 두 줄이다.
INSERT INTO profiles (member_id, nickname, created_at, updated_at)
SELECT id, nickname, created_at, updated_at
FROM members;
